---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LoanSens.
--- DateTime: 20/06/2018 21:05
---

require("class")

Creature = class(function(this, screen, neurons, p1)
    this.drawScreen = screen
    this.neurons = neurons -- Make a copy ?
    this.p1 = p1
end)

function Creature:updateNeurons()
    -- Update all input to unpressed
    for _, v in pairs(inputsNes) do
        self.p1.fields[v]:set_value(0)
    end
    -- Neuron them self press any button they are map to if needed
    for _, v in pairs(self.neurons) do
        v:check()
    end
end

function Creature:draw()
    for _, v in pairs(self.neurons) do
        v:draw(self.drawScreen)
    end
end

function Creature:__tostring()
    local ret = ""
    ret = ret .. "Neurons : "
    for _, v in pairs(self.neurons) do
        ret = ret .. "\t" .. v .. "\n"
    end
    return ret
end