---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Loan.
--- DateTime: 24/06/2018 17:52
---
local MameCst = require("mameLuaConstants")
require("class")
require("creature")

Generation = class(function (this, size, map, inputsManager)
    this.creatures = {}
    this.size = size

    for i = 1, size do
        local randomCreature = Creature(map, inputsManager, {}, MameCst.screen, MameCst.ioP1, 160, 4)
        table.insert(this.creatures, randomCreature)
    end

    this.currentCreatureCounter = 0
end)

function Generation:randomizeAll()
    for i = 1, self.size do
        self.creatures[i]:randomize(i)
    end
end

function Generation:getNextCreature()
    self.currentCreatureCounter = self.currentCreatureCounter + 1
    return self.creatures[self.currentCreatureCounter]
end

function Generation:__tostring()
    local ret = ""
    for i, v in pairs(self.creatures) do
        ret = ret .. i .. " : " .. tostring(v) .. "\n"
    end
    return ret
end
