---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Loan.
--- DateTime: 24/06/2018 17:52
---
local MameCst = require("mameLuaConstants")
require("class")
require("creature")

local currentCreature = nil

Generation = class(function (this, size, map, inputsManager)
    this.creatures = {}
    this.size = size

    for i = 1, size do
        local randomCreature = Creature(map, inputsManager, {}, MameCst.screen, MameCst.ioP1, 160, 4)
        randomCreature:randomize()
        table.insert(this.creatures, randomCreature)
    end
end)

function Generation:testCreatures()
    for i, v in pairs(self.creatures) do
        self:testCreature(v)
    end
end

function Generation:testCreature(creature)
    MameCst.machine:load("start")
    while currentCreature == nil do
        currentCreature = creature
    end
end

