---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LoanSens.
--- DateTime: 20/06/2018 21:22
---

inputsNes = {"P1 Right", "P1 Left", "P1 Down", "P1 Up","P1 Start", "P1 Select", "B", "A"}

Inputs = class(function(this, screen, xOffset, yOffset, squareSize, space)
    this.drawScreen = screen
    this.drawXOffset = xOffset
    this.drawYOffset = yOffset
    this.drawSquareSize = squareSize
    this.drawSpace = space
end)

function Inputs:draw()
    for _, v in ipairs(inputsNes) do
        self:drawInput(v)
    end
end

function Inputs:isInputPress(inputNes)
    local currentPressInput = MameCst.ioP1:read()
    local bitVal = (2^(#inputsNes-inputNes))
    local isPressed = currentPressInput & bitVal == bitVal
    return isPressed
end

function Inputs:drawInput(input)
    local boxColor = 0x80ffffff
    if self:isInputPress(input) then
        boxColor = 0xcc000000
    end

    -- TODO
end


