---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Loan.
--- DateTime: 29/06/2018 16:55
---

require("class")
local MameCst = require("mameLuaConstants")

MameController = class(function (this, map, inputsManager, generation, timeOutDelay)
    this.map = map
    this.inputsManager = inputsManager
    this.gen = generation
    this.timeOutDelay = timeOutDelay

    this.creature = nil
    this.lastFitness = nil
    this.timer = nil
    this.lastTimeOut = nil

    this:askNextCreature()
end)

function MameController:askNextCreature()
    MameCst.machine:load("start")
    self.creature = self.gen:getNextCreature()
    self.lastFitness = 0
    self.timer = 0
    self.lastTimeOut = 0
end

function MameController:registerFrame()
    MameCst.emu.register_frame(
            function()
                self.timer = self.timer + 1
                -- Go to next creature if dead, or timeout keeping the same fitness
                local isTimeOut = self.timer - self.lastTimeOut >= 60 * self.timeOutDelay
                local curFitness = self.creature:getFitness()
                local isCreatureDead = self.creature:isDead()
                local isNoProgress = isTimeOut and self.lastFitness == curFitness
                if (isCreatureDead or isNoProgress) then
                    self.gen:creatureIsDead()
                    self:askNextCreature()
                    if isCreatureDead and isNoProgress then
                        print("Creature died & timeout")
                    elseif isCreatureDead then
                        print("Creature died")
                    elseif isNoProgress then
                        print("Creature timeout")
                    else
                        print("Creature died for Unknown reason")
                    end
                elseif (isTimeOut and self.lastFitness ~= curFitness) then
                    self.lastFitness = curFitness
                    self.lastTimeOut = self.timer
                end

                self.map:update()
                self.creature:updateFitness()
                self.creature:updateNeurons()
            end
    )
end

function MameController:registerFrameDone()
    MameCst.emu.register_frame_done(
            function()
                self.map:draw()
                self.inputsManager:draw()
                if self.creature ~= nil then
                    self.creature:draw()
                end
                self.gen:draw()
            end
    )
end
