---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LoanSens.
--- DateTime: 20/06/2018 21:09
---

require("class")

Neuron = class(function(this, tile, inputsManager, inputIdx)
    this.tile = tile
    this.inputMan = inputsManager
    this.inputIdx = inputIdx
end)

function Neuron:draw(screen)
    local tileX = self.tile:getDrawCenterX()
    local tileY = self.tile:getDrawCenterY()

    local inputX = self.inputMan:getDrawCenterX(self.inputIdx)
    local inputY = self.inputMan:getDrawCenterY(self.inputIdx)

    screen:draw_line(tileX, tileY, inputX, inputY, 0xffffffff)
end

function Neuron:__tostring()
    local ret = ""
    ret = ret .. "<" .. self.tile .. ", " .. self.input .. ">"
    return ret
end