---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LoanSens.
--- DateTime: 30/03/2018 22:17
---

print(tostring(true))

function printMatrix(matrix, w, h)
    for i=1, h do
        s2 = ""
        for j=1, w do
            tileAdr = tilesStart + (i-1)*16 + (j-1)
            if (j > 16) then
                tileAdr = tileAdr + (w/2) * (h-1)
            end
            s2 = s2 .. tileAdr .. " \t"
        end
        print(s2)
    end
end

tilesStart = 0x0500
tilesEnd = 0x069F
tilesW = 32
tilesH = 13

tilesSolid = {}
for i=1, tilesH do
    tilesSolid[i] = {}
    for j=1, tilesW do
        tilesSolid[i][j] = nil
    end
end

printMatrix(tilesSolid, tilesW, tilesH)